/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/forgot`; params?: Router.UnknownInputParams; } | { pathname: `/getstarted`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/notif_counter` | `/notif_counter`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/forgot`; params?: Router.UnknownOutputParams; } | { pathname: `/getstarted`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landing`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/categories` | `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/services` | `/services`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(users)'}/notif_counter` | `/notif_counter`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/forgot${`?${string}` | `#${string}` | ''}` | `/getstarted${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landing${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/categories${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/services${`?${string}` | `#${string}` | ''}` | `/services${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(users)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(users)'}/notif_counter${`?${string}` | `#${string}` | ''}` | `/notif_counter${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/forgot`; params?: Router.UnknownInputParams; } | { pathname: `/getstarted`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landing`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/categories` | `/categories`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/services` | `/services`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(users)'}/notif_counter` | `/notif_counter`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
